### ISSUE TITLE
Unable to execute the selected tool.

### ISSUE THREAD

**Issue by epidemicjul** [Esri/python-toolbox-for-rapid#6]
Hello, I am a employee from Hydromet of Belarus. We are trying to start wrf hydro model and need for that your preprocessor. 
But I have problem conneced with this scripts.
When I enter them there is error "Unable to execute the selected tool. You do not have the necessary license to execute the selected tool". 
I use ArcGIS 10.3.1, Python 2.7. And have choosen Spatial Analyst in Extensions. 
![2017 05 15 14-24-56](https://cloud.githubusercontent.com/assets/28704318/26055602/46f15cb0-397a-11e7-9645-c47c985be3ae.jpg)
![2017 05 15 14-26-16](https://cloud.githubusercontent.com/assets/28704318/26055641/65423b8a-397a-11e7-8b85-a263fcebaac0.jpg)

**Comment by snowman2** [comment]
Do you have the Advanced license checked out?

**Comment by epidemicjul** [comment]
yes, I have the advanced license

![2017 05 16 08-41-52](https://cloud.githubusercontent.com/assets/28704318/26091441/f4ac10fe-3a13-11e7-8833-d9bd1b3c812b.jpg)

**Comment by epidemicjul** [comment]
We also try to use scripts on ArcGIS 10.5 (Trial License 60 days), scripts does not work too.

**Comment by epidemicjul** [comment]
Hi, I have solved my problem. 
This problem was becouse we had license only for ArcGIS Desktop, but not for Spatial Analyst.

**Comment by jiaqizhang211** [comment]
Hello Dr Snow,
I'm having the similar issue of connecting with this script. I use ArcGIS 10.3 and have the Advanced License and spatial analyst checked out. I also install the netCDF4 package. But when I tried to add this toolbox, it always showed the red cross icon on the toolbox as below and cannot be added. Do you have any idea what's the potential cause for this?
![image](https://user-images.githubusercontent.com/29763949/27664614-24cdeb72-5c2e-11e7-8924-b47c9032c283.png)

**Comment by dengding** [comment]
@jiaqizhang211 Could you try the following in your ArcMap just to double check netCDF4 is installed and Spatial Analyst extention is checked out successfully?
1. From python window in ArcMap, run the following
import netCDF4
2. Open any tool in Spatial Analyst from ArcToolbox.

**Comment by jiaqizhang211** [comment]
@dengding The netCDF4 can be imported as shown below. And the tool in Spatial Analyst from ArcToolbox can be opened. I also tried to add this toolbox on ArcGIS 10.4. However, the red cross icon remains.
![image](https://user-images.githubusercontent.com/29763949/27693311-b305bdae-5cae-11e7-9f3a-924a107a1e42.png)
![image](https://user-images.githubusercontent.com/29763949/27693476-2e1a6a08-5caf-11e7-9265-fed92c9b773d.png)

**Comment by jiaqizhang211** [comment]
@dengding Thanks for your help. I double checked other environments and found out that the Arc Hydro was not installed correctly. I re-install the Arc Hydro and problem is solved.
